### PR TITLE
Gate js-sys dependency behind 'wasm-bindgen' feature (#496)

### PR DESCRIPTION
**Pull request by xy2iii**
This pr fixes the breaking change of time 0.3.12.

### CODE REVIEW

**Comment by autodidaddict** [comment]
This just broke a handful of builds for us as well. Commenting here to keep the issue bumped.

**Comment by stevelr** [comment]
I'm getting a build error 
```
   |
59 |     pub fn now_utc() -> Self {
   |            -------      ^^^^ expected struct `OffsetDateTime`, found `()`
   |            |
   |            implicitly returns `()` as its body has no tail or `return` expression
```

**Comment by Goorzhel** [comment]
No build errors here but I was wondering why my `time`-using crate suddenly started pulling in `js-sys`:
```diff
 [[package]]
 name = "time"
-version = "0.3.11"
+version = "0.3.12"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "72c91f41dcb2f096c05f0873d667dceec1087ce5bcf984ec8ffb19acddbb3217"
+checksum = "74b7cc93fc23ba97fde84f7eea56c55d1ba183f495c6715defdfc7b9cb8c870f"
 dependencies = [
  "itoa",
+ "js-sys",
  "libc",
  "num_threads",
  "time-macros",
```

**Comment by jhpratt** [comment]
@brooksmtownsend The PR has only been open a couple days. I will review it when I get the chance. I am well aware that this broke some things.

**Comment by stevelr** [comment]
Thanks @xy2iii that latest change works for wasm32-unknown-unknown.

**Review by jhpratt — APPROVED** [review]
LGTM; merging.

**Pull request merged**
