### PR TITLE
Add no-alloc support

### PR DESCRIPTION
**Pull request by garasubo**
Solve #249 

Add `alloc` feature to support no_std targets.
Confirmed that the build passed in my no_std application

### CODE REVIEW

**Comment by garasubo** [comment]
One concern is in no_std build, there is an warning from Error Enum
```
warning: enum variant is more than three times larger (52 bytes) than the next largest
   --> src/format/parse.rs:66:5
    |
66  |     ComponentOutOfRange(error::ComponentRange),
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> src/lib.rs:141:5
    |
141 |     variant_size_differences
    |     ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jhpratt** [comment]
Would you mind adding this to CI? This should amount to removing the `alloc` in the list of features to ignore and always be present — this is on a few lines in the workflow file.

The only other thing I have to note (assuming CI passes once it's done) is that it would be best to remove the `Box` entirely. If this weren't the case, even requiring the `alloc` feature via a transitive dependency could break preëxisting code.

With regard to the lint, feel free to silence it, as there's not really anything actionable.

**Comment by garasubo** [comment]
TODO: remove unused import when all features are disabled

**Comment by garasubo** [comment]
Removed all unused imports.

Currently, format module cannot use in no-std mode without alloc because it depends on `String` and `ToString`.

**Comment by jhpratt** [comment]
Would you mind rebasing this? It looks like there's a couple merge conflicts currently. That should also cause the CI to run, since it didn't on the most recent commit (not sure why).

**Comment by garasubo** [comment]
Rebased my branch to the latest v0.3 branch

**Comment by jhpratt** [comment]
Looks like there's still some unused imports in addition to some lints that could be addressed. Feel free to silence the missing `Copy` warning on `Error` (but not `error::Parse`).

**Comment by garasubo** [comment]
> Looks like there's still some unused imports in addition to some lints that could be addressed. 

Which one? In my env, I didn't see any unused imports in `cargo build`, `cargo build --all-features` and `cargo build --no-default-features`

**Comment by jhpratt** [comment]
Take a look at the CI output; it runs the full powerset of features.

**Comment by garasubo** [comment]
Rebased my branch and fixed the unused import issue

**Comment by jhpratt** [comment]
Looks like aside from formatting (`cargo +nightly fmt` will suffice), `Copy` should still be derived on `error::Parse`, with the remaining clippy lints silenced.

**Comment by garasubo** [comment]
Added `Copy` for `parse::Error`

**Comment by garasubo** [comment]
@jhpratt Do you want me to format this? I assumed that I don't have to do it because the original issue said so.
I believe I resolved any other issues.

**Comment by jhpratt** [comment]
When I referenced formatting, I meant the formatting/parsing parts of the time crate, not rustfmt. Sorry for the confusion via ambiguous wording. Either way, I can handle rustfmt when cleaning up history. Looks like there's a couple lints that are still unhandled, as well as an unexpected `#[derive(Copy)]` on the generic `error::Error` type.

I'll likely clean up the commit history and make the remaining changes myself at some point, as my requests for changes frankly don't seem to be going anywhere.

**Comment by jhpratt** [comment]
doc_cfg annotations will need to be added at some point, but I'll likely do that at a later point.

**Review by jhpratt — APPROVED** [review]

**Pull request merged**
