### PR TITLE
Use tz-rs to obtain the system's UTC offset

### PR DESCRIPTION
**Pull request by clia**
If this is an annoying PR, please ignore it!

### CODE REVIEW

**Comment by jhpratt** [comment]
This is something I planned to look into at some point. It's a _very_ large change and will necessitate me doing an in-depth review of the full `tz-rs` crate. Setting that aside, it looks like the crate requires a newer version of Rust that `time` cannot yet use per policy. Closing for that reason.

**Comment by clia** [comment]
It's OK! We all support your hard work!

For now I made a temporary crate [clia-time](https://crates.io/crates/clia-time) for myself and will have a try.

**Comment by jhpratt** [comment]
Please update the README to indicate that there is no relation to this crate.

**Comment by clia** [comment]
Updated.

**Comment by x-hgg-x** [comment]
For information, I have reduced the MSRV to `rustc 1.45` for the version `v0.6.6` of `tz-rs`.

**Comment by jhpratt** [comment]
Awesome. I'll take a look at some point. Ultimately it's still probably unlikely because it's such a large change, plus the tz-rs crate doesn't seem too stable. Rust is getting close to a satisfactory solution that would permit me to soundly expose the existing functionality.

**Pull request closed without merging**
